name: Docker cache build

on:
  push:
    branches:
      - main

jobs:
  docker-cache:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-cache.yaml@main
    with:
      DOCKER_IMAGE_NAME: nbc-demo-hub
      DOCKERFILE_NAME: ./frontend/Dockerfile.cache
      DOCKER_CONTEXT: ./frontend

