name: Docker production build

on:
  push:
    tags:
      - 'v[12].[0-9]+.[0-9]+'

jobs:
  build-nbc-demo-hub-production:
    uses: TrustlessComputer/tc-github-action-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      DOCKER_IMAGE_NAME: nbc-demo-hub
      DOCKERFILE_NAME: ./frontend/Dockerfile.cache
      DOCKER_CONTEXT: ./frontend
      CONCURRENCY_GROUP: docker_build_production
      RUNNER_TAG: ubuntu-latest
    secrets:
      GCLOUD_DEV_SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_DEV_SERVICE_ACCOUNT_JSON }}
